DATA SEGMENT
    NUM1 DB 0058H
    NUM2 DB -19H
    PROD DB 3 DUP<0>
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA 
    START:MOV AX,DATA
    MOV DS,AX
    MOV AL,NUM1; FIRST NUMBER LOADED IN AL
    MOV BL,NUM2; SECOND NUMBVER LOADED IN B
    IMUL BL; MULTIPLYING BL  with AL, IMUL TAKES CARE OF SIGNED NUMBERS
    MOV PROD,AL; MOVING THE ANSWER TO  PROD VARIABLE
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
